### ISSUE TITLE
Purchase profit is still possible (tried and tested)

### ISSUE THREAD

**Issue by ItsGreyToday** [arramus/Snufkin-Weapons-Xpansion-A19-2021May21#1]
I'm assuming you guys didn't try full bartering, in which case means having eaten/equipped the following:

1. **Better Barter** skill perk level 5 (25%)
2. **Grandpa's Awesome Sauce** (20%)
3. **Cigar**/**Cigarette** (10%)
4. **Sugar Butts** (10%)
5. **Wagon Wheel Mod** (10%)
6. **Pumpkin Cheesecake** (5%)
7. **.44 Magnum** equipped in hotbar, having read **Magnum Enforcer Vol 4** (5%)

having all of these will still allow a player to sell something and buy it at a lower price, eventually being able to get infinite dukes, brass, exp.

**Comment by arramus** [comment]
Thanks for reporting.

Yes, this is an issue that rears its head for higher level bartering Skill Perks with a full combination of buffs, but until then it is not an issue, and at that stage of game play dukes are already being horded and any more will have minimal impact.

In the whole scheme of things, Server Admin consider the Wagon Wheel to be a fun item that should remain regardless of this issue as it serves lower level players very well. In fact, some will scold me for this change and return the benefit to 20% because their loot probability is incredibly lower than default and they would like players to fully benefit regardless. By the time a player reaches barter skill 5 and has access to all other buffs and uses them in full combination, limited access to funds is rarely a game feature and hording of dukes has already begun. Any further hording through the Wagon Wheel is personal choice.

It had been a known issue for some time and a number of players reported it by private message. Yesterday was the very first time it was publicly raised in TFP forum which forced a response. Reducing from 20% - 10% was purely a token gesture response now that the cat is out of the bag. Fortunately the forum poster only mentioned a few of the buffs they tried in combination. Players will still try them all, if they haven't already.

Totally removing the Wagon Wheel from the mod is an option, but Server Admin we discussed this with (Tipsy Gaming, ZombieShack; the first to report it, and Geek Gaming, among others) see it as a minor issue and feel the benefit outweighs the higher level exploit. They would also rather not deal with upgrading mid World because it causes issues with item IDs and player's inventories. Where this has been raised, typically quietly in the past, it was suggested to remove the item from just the Loot box list as this is the only way to gain this item or manually decrease the gain to take effect on restart.

Now this has been raised publicly, and out of courtesy for the time you took to test the full combination and post about it publicly, this post will remain as a valuable resource for Server Admin who take the time to delve. With A20, we shall see where this heads depending on if the Vanilla bartering features change. Until then, it is what it is with Server Admin being pretty savvy for 7 Days and knowing what to change should they wish to tweak the settings to their own server specifications.
